###create projct
POST http://localhost:3000/project/create
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "title" : "myPRJ",
    "text" : "text of the new project"
}
###get all projct
GET  http://localhost:3000/project/list
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

###get projct by id
GET http://localhost:3000/project/6378ee931d3178b4467000be
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

###remove projct by id
DELETE http://localhost:3000/project/remove/6378ee931d3178b4467000be
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json